[package]
name = "drm-playready-format"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
drm-core = { path = "../core" }
data-encoding = "2"
quick-xml = "0.37"
thiserror = "2"
